const stations_dict = {
    'Jurong East' : ['NS1', 'EW24'] ,
    'Bukit Batok' : ['NS2'] ,
    'Bukit Gombak' : ['NS3'] ,
    'Choa Chu Kang' : ['NS4', 'BP1'] ,
    'Yew Tee' : ['NS5'] ,
    'Kranji' : ['NS7'] ,
    'Marsiling' : ['NS8'] ,
    'Woodlands' : ['NS9'] ,
    'Admiralty' : ['NS10'] ,
    'Sembawang' : ['NS11'] ,
    'Canberra' : ['NS12'] ,
    'Yishun' : ['NS13'] ,
    'Khatib' : ['NS14'] ,
    'Yio Chu Kang' : ['NS15'] ,
    'Ang Mo Kio' : ['NS16'] ,
    'Bishan' : ['NS17', 'CC15'] ,
    'Braddell' : ['NS18'] ,
    'Toa Payoh' : ['NS19'] ,
    'Novena' : ['NS20'] ,
    'Newton' : ['NS21', 'DT11'] ,
    'Orchard' : ['NS22', 'TE14'] ,
    'Somerset' : ['NS23'] ,
    'Dhoby Ghaut' : ['NS24', 'NE6', 'CC1'] ,   
    'City Hall' : ['NS25', 'EW13'] ,
    'Raffles Place' : ['NS26', 'EW14'] ,       
    'Marina Bay' : ['NS27', 'CE2', 'TE20'] ,   
    'Marina South Pier' : ['NS28'] ,
    'Pasir Ris' : ['EW1'] ,
    'Tampines' : ['EW2', 'DT32'] ,
    'Simei' : ['EW3'] ,
    'Tanah Merah' : ['EW4', 'CG'] ,
    'Bedok' : ['EW5'] ,
    'Kembangan' : ['EW6'] ,
    'Eunos' : ['EW7'] ,
    'Paya Lebar' : ['EW8', 'CC9'] ,
    'Aljunied' : ['EW9'] ,
    'Kallang' : ['EW10'] ,
    'Lavender' : ['EW11'] ,
    'Bugis' : ['EW12', 'DT14'] ,
    'Tanjong Pagar' : ['EW15'] ,
    'Outram Park' : ['EW16', 'NE3', 'TE17'] ,  
    'Tiong Bahru' : ['EW17'] ,
    'Redhill' : ['EW18'] ,
    'Queenstown' : ['EW19'] ,
    'Commonwealth' : ['EW20'] ,
    'Buona Vista' : ['EW21', 'CC22'] ,
    'Dover' : ['EW22'] ,
    'Clementi' : ['EW23'] ,
    'Chinese Garden' : ['EW25'] ,
    'Lakeside' : ['EW26'] ,
    'Boon Lay' : ['EW27'] ,
    'Pioneer' : ['EW28'] ,
    'Joo Koon' : ['EW29'] ,
    'Gul Circle' : ['EW30'] ,
    'Tuas Crescent' : ['EW31'] ,
    'Tuas West Road' : ['EW32'] ,
    'Tuas Link' : ['EW33'] ,
    'Expo' : ['CG1', 'DT35'] ,
    'Changi Airport' : ['CG2'] ,
    'HarbourFront' : ['NE1', 'CC29'] ,
    'Chinatown' : ['NE4', 'DT19'] ,
    'Clarke Quay' : ['NE5'] ,
    'Little India' : ['NE7', 'DT12'] ,
    'Farrer Park' : ['NE8'] ,
    'Boon Keng' : ['NE9'] ,
    'Potong Pasir' : ['NE10'] ,
    'Woodleigh' : ['NE11'] ,
    'Serangoon' : ['NE12', 'CC13'] ,
    'Kovan' : ['NE13'] ,
    'Hougang' : ['NE14'] ,
    'Buangkok' : ['NE15'] ,
    'Sengkang' : ['NE16', 'SW', 'SE', 'STC'] , 
    'Punggol' : ['NE17', 'PW', 'PE', 'PTC'] ,  
    'Bras Basah' : ['CC2'] ,
    'Esplanade' : ['CC3'] ,
    'Promenade' : ['CC4', 'CE', 'DT15'] ,      
    'Nicoll Highway' : ['CC5'] ,
    'Stadium' : ['CC6'] ,
    'Mountbatten' : ['CC7'] ,
    'Dakota' : ['CC8'] ,
    'MacPherson' : ['CC10', 'DT26'] ,
    'Tai Seng' : ['CC11'] ,
    'Bartley' : ['CC12'] ,
    'Lorong Chuan' : ['CC14'] ,
    'Marymount' : ['CC16'] ,
    'Caldecott' : ['CC17', 'TE9'] ,
    'Botanic Gardens' : ['CC19', 'DT9'] ,      
    'Farrer Road' : ['CC20'] ,
    'Holland Village' : ['CC21'] ,
    'one-north' : ['CC23'] ,
    'Kent Ridge' : ['CC24'] ,
    'Haw Par Villa' : ['CC25'] ,
    'Pasir Panjang' : ['CC26'] ,
    'Labrador Park' : ['CC27'] ,
    'Telok Blangah' : ['CC28'] ,
    'Bayfront' : ['CE1', 'DT16'] ,
    'Bukit Panjang' : ['DT1', 'BP6'] ,
    'Cashew' : ['DT2'] ,
    'Hillview' : ['DT3'] ,
    'Beauty World' : ['DT5'] ,
    'King Albert Park' : ['DT6'] ,
    'Sixth Avenue' : ['DT7'] ,
    'Tan Kah Kee' : ['DT8'] ,
    'Stevens' : ['DT10', 'TE11'] ,
    'Rochor' : ['DT13'] ,
    'Downtown' : ['DT17'] ,
    'Telok Ayer' : ['DT18'] ,
    'Fort Canning' : ['DT20'] ,
    'Bencoolen' : ['DT21'] ,
    'Jalan Besar' : ['DT22'] ,
    'Bendemeer' : ['DT23'] ,
    'Geylang Bahru' : ['DT24'] ,
    'Mattar' : ['DT25'] ,
    'Ubi' : ['DT27'] ,
    'Kaki Bukit' : ['DT28'] ,
    'Bedok North' : ['DT29'] ,
    'Bedok Reservoir' : ['DT30'] ,
    'Tampines West' : ['DT31'] ,
    'Tampines East' : ['DT33'] ,
    'Upper Changi' : ['DT34'] ,
    'South View' : ['BP2'] ,
    'Keat Hong' : ['BP3'] ,
    'Teck Whye' : ['BP4'] ,
    'Phoenix' : ['BP5'] ,
    'Petir' : ['BP7'] ,
    'Pending' : ['BP8'] ,
    'Bangkit' : ['BP9'] ,
    'Fajar' : ['BP10'] ,
    'Segar' : ['BP11'] ,
    'Jelapang' : ['BP12'] ,
    'Senja' : ['BP13'] ,
    'Compassvale' : ['SE1'] ,
    'Rumbia' : ['SE2'] ,
    'Bakau' : ['SE3'] ,
    'Kangkar' : ['SE4'] ,
    'Ranggung' : ['SE5'] ,
    'Cheng Lim' : ['SW1'] ,
    'Farmway' : ['SW2'] ,
    'Kupang' : ['SW3'] ,
    'Thanggam' : ['SW4'] ,
    'Fernvale' : ['SW5'] ,
    'Layar' : ['SW6'] ,
    'Tongkang' : ['SW7'] ,
    'Renjong' : ['SW8'] ,
    'Cove' : ['PE1'] ,
    'Meridian' : ['PE2'] ,
    'Coral Edge' : ['PE3'] ,
    'Riviera' : ['PE4'] ,
    'Kadaloor' : ['PE5'] ,
    'Oasis' : ['PE6'] ,
    'Damai' : ['PE7'] ,
    'Sam Kee' : ['PW1'] ,
    'Punggol Point' : ['PW3'] ,
    'Samudera' : ['PW4'] ,
    'Nibong' : ['PW5'] ,
    'Sumang' : ['PW6'] ,
    'Soo Teck' : ['PW7'] ,
    'Woodlands North ' : ['TE1'] ,
    'Woodlands ' : ['TE2'] ,
    'Woodlands South ' : ['TE3'] ,
    'Springleaf' : ['TE4'] ,
    'Lentor' : ['TE5'] ,
    'Mayflower' : ['TE6'] ,
    'Bright Hill' : ['TE7'] ,
    'Upper Thomson' : ['TE8'] ,
    'Napier' : ['TE12'] ,
    'Orchard Boulevard' : ['TE13'] ,
    'Great World' : ['TE15'] ,
    'Havelock' : ['TE16'] ,
    'Maxwell' : ['TE18'] ,
    'Shenton Way' : ['TE19'] ,
    'Gardens by the Bay' : ['TE22'] ,
}

const lines = {
    'NS' : ['NS1', 'NS2', 'NS3', 'NS4', 'NS5', 'NS7', 'NS8', 'NS9', 'NS10', 'NS11', 'NS12', 'NS13', 'NS14', 'NS15', 'NS16', 'NS17', 'NS18', 'NS19', 'NS20', 'NS21', 'NS22', 'NS23', 'NS24', 'NS25', 'NS26', 'NS27', 'NS28'] ,
    'EW' : ['EW1', 'EW2', 'EW3', 'EW4', 'EW5', 'EW6', 'EW7', 'EW8', 'EW9', 'EW10', 'EW11', 'EW12', 'EW13', 'EW14', 'EW15', 'EW16', 'EW17', 'EW18', 'EW19', 'EW20', 'EW21', 'EW22', 'EW23', 'EW24', 'EW25', 'EW26', 'EW27', 'EW28', 'EW29', 'EW30', 'EW31', 'EW32', 'EW33'] ,
    'CG' : ['CG1', 'CG2'] ,
    'NE' : ['NE1', 'NE3', 'NE4', 'NE5', 'NE6', 'NE7', 'NE8', 'NE9', 'NE10', 'NE11', 'NE12', 'NE13', 'NE14', 'NE15', 'NE16', 'NE17'] ,
    'CC' : ['CC1', 'CC2', 'CC3', 'CC4', 'CC5', 'CC6', 'CC7', 'CC8', 'CC9', 'CC10', 'CC11', 'CC12', 'CC13', 'CC14', 'CC15', 'CC16', 'CC17', 'CC19', 'CC20', 'CC21', 'CC22', 'CC23', 'CC24', 'CC25', 'CC26', 'CC27', 'CC28', 'CC29'] ,
    'CE' : ['CE1', 'CE2'] ,
    'DT' : ['DT1', 'DT2', 'DT3', 'DT5', 'DT6', 'DT7', 'DT8', 'DT9', 'DT10', 'DT11', 'DT12', 'DT13', 'DT14', 'DT15', 'DT16', 'DT17', 'DT18', 'DT19', 'DT20', 'DT21', 'DT22', 'DT23', 'DT24', 'DT25', 'DT26', 'DT27', 'DT28', 'DT29', 'DT30', 'DT31', 'DT32', 'DT33', 'DT34', 'DT35'] ,
    'BP' : ['BP1', 'BP2', 'BP3', 'BP4', 'BP5', 'BP6', 'BP7', 'BP8', 'BP9', 'BP10', 'BP11', 'BP12', 'BP13'] ,
    'ST' : ['STC'] ,
    'SE' : ['SE1', 'SE2', 'SE3', 'SE4', 'SE5'] ,
    'SW' : ['SW1', 'SW2', 'SW3', 'SW4', 'SW5', 'SW6', 'SW7', 'SW8'] ,
    'PT' : ['PTC'] ,
    'PE' : ['PE1', 'PE2', 'PE3', 'PE4', 'PE5', 'PE6', 'PE7'] ,
    'PW' : ['PW1', 'PW3', 'PW4', 'PW5', 'PW6', 'PW7'] ,
    'TE' : ['TE1', 'TE2', 'TE3', 'TE4', 'TE5', 'TE6', 'TE7', 'TE8', 'TE9', 'TE11', 'TE12', 'TE13', 'TE14', 'TE15', 'TE16', 'TE17', 'TE18', 'TE19', 'TE20', 'TE22'] ,
}

const travelTime = {

}

module.exports = {
    stations_dict,
    lines,
    travelTime
}