const stations_dict = {
    'Jurong East' : ['NS1', 'EW24'],
    'Bukit Batok' : ['NS2'],
    'Bukit Gombak' : ['NS3'],
    'Choa Chu Kang' : ['NS4', 'BP1_a', 'BP1_b'],
    'Yew Tee' : ['NS5'],
    'Kranji' : ['NS7'],
    'Marsiling' : ['NS8'],
    'Woodlands' : ['NS9', 'TE2'],
    'Admiralty' : ['NS10'],
    'Sembawang' : ['NS11'],
    'Canberra' : ['NS12'],
    'Yishun' : ['NS13'],
    'Khatib' : ['NS14'],
    'Yio Chu Kang' : ['NS15'],
    'Ang Mo Kio' : ['NS16'],
    'Bishan' : ['NS17', 'CC15'],
    'Braddell' : ['NS18'],
    'Toa Payoh' : ['NS19'],
    'Novena' : ['NS20'],
    'Newton' : ['NS21', 'DT11'],
    'Orchard' : ['NS22', 'TE14'],
    'Somerset' : ['NS23'],
    'Dhoby Ghaut' : ['NS24', 'NE6', 'CC1'],
    'City Hall' : ['NS25', 'EW13'],
    'Raffles Place' : ['NS26', 'EW14'],
    'Marina Bay' : ['NS27', 'CE2', 'TE20'],
    'Marina South Pier' : ['NS28'],
    'Pasir Ris' : ['EW1'],
    'Tampines' : ['EW2', 'DT32'],
    'Simei' : ['EW3'],
    'Tanah Merah' : ['EW4', 'CG'],
    'Bedok' : ['EW5'],
    'Kembangan' : ['EW6'],
    'Eunos' : ['EW7'],
    'Paya Lebar' : ['EW8', 'CC9'],
    'Aljunied' : ['EW9'],
    'Kallang' : ['EW10'],
    'Lavender' : ['EW11'],
    'Bugis' : ['EW12', 'DT14'],
    'Tanjong Pagar' : ['EW15'],
    'Outram Park' : ['EW16', 'NE3', 'TE17'],
    'Tiong Bahru' : ['EW17'],
    'Redhill' : ['EW18'],
    'Queenstown' : ['EW19'],
    'Commonwealth' : ['EW20'],
    'Buona Vista' : ['EW21', 'CC22'],
    'Dover' : ['EW22'],
    'Clementi' : ['EW23'],
    'Chinese Garden' : ['EW25'],
    'Lakeside' : ['EW26'],
    'Boon Lay' : ['EW27'],
    'Pioneer' : ['EW28'],
    'Joo Koon' : ['EW29'],
    'Gul Circle' : ['EW30'],
    'Tuas Crescent' : ['EW31'],
    'Tuas West Road' : ['EW32'],
    'Tuas Link' : ['EW33'],
    'Expo' : ['CG1', 'DT35'],
    'Changi Airport' : ['CG2'],
    'HarbourFront' : ['NE1', 'CC29'],
    'Chinatown' : ['NE4', 'DT19'],
    'Clarke Quay' : ['NE5'],
    'Little India' : ['NE7', 'DT12'],
    'Farrer Park' : ['NE8'],
    'Boon Keng' : ['NE9'],
    'Potong Pasir' : ['NE10'],
    'Woodleigh' : ['NE11'],
    'Serangoon' : ['NE12', 'CC13'],
    'Kovan' : ['NE13'],
    'Hougang' : ['NE14'],
    'Buangkok' : ['NE15'],
    'Sengkang' : ['NE16', 'STC_A', 'STC_B', 'STC_C', 'STC_D'],
    'Punggol' : ['NE17', 'PTC_A', 'PTC_B', 'PTC_C', 'PTC_D'],
    'Bras Basah' : ['CC2'],
    'Esplanade' : ['CC3'],
    'Promenade' : ['CC4', 'CE', 'DT15'],
    'Nicoll Highway' : ['CC5'],
    'Stadium' : ['CC6'],
    'Mountbatten' : ['CC7'],
    'Dakota' : ['CC8'],
    'MacPherson' : ['CC10', 'DT26'],
    'Tai Seng' : ['CC11'],
    'Bartley' : ['CC12'],
    'Lorong Chuan' : ['CC14'],
    'Marymount' : ['CC16'],
    'Caldecott' : ['CC17', 'TE9'],
    'Botanic Gardens' : ['CC19', 'DT9'],
    'Farrer Road' : ['CC20'],
    'Holland Village' : ['CC21'],
    'one-north' : ['CC23'],
    'Kent Ridge' : ['CC24'],
    'Haw Par Villa' : ['CC25'],
    'Pasir Panjang' : ['CC26'],
    'Labrador Park' : ['CC27'],
    'Telok Blangah' : ['CC28'],
    'Bayfront' : ['CE1', 'DT16'],
    'Bukit Panjang' : ['DT1', 'BP6_a', 'BP6_b'],
    'Cashew' : ['DT2'],
    'Hillview' : ['DT3'],
    'Beauty World' : ['DT5'],
    'King Albert Park' : ['DT6'],
    'Sixth Avenue' : ['DT7'],
    'Tan Kah Kee' : ['DT8'],
    'Stevens' : ['DT10', 'TE11'],
    'Rochor' : ['DT13'],
    'Downtown' : ['DT17'],
    'Telok Ayer' : ['DT18'],
    'Fort Canning' : ['DT20'],
    'Bencoolen' : ['DT21'],
    'Jalan Besar' : ['DT22'],
    'Bendemeer' : ['DT23'],
    'Geylang Bahru' : ['DT24'],
    'Mattar' : ['DT25'],
    'Ubi' : ['DT27'],
    'Kaki Bukit' : ['DT28'],
    'Bedok North' : ['DT29'],
    'Bedok Reservoir' : ['DT30'],
    'Tampines West' : ['DT31'],
    'Tampines East' : ['DT33'],
    'Upper Changi' : ['DT34'],
    'South View' : ['BP2_a', 'BP2_b'],
    'Keat Hong' : ['BP3_a', 'BP3_b'],
    'Teck Whye' : ['BP4_a', 'BP4_b'],
    'Phoenix' : ['BP5_a', 'BP5_b'],
    'Petir' : ['BP7'],
    'Pending' : ['BP8'],
    'Bangkit' : ['BP9'],
    'Fajar' : ['BP10'],
    'Segar' : ['BP11'],
    'Jelapang' : ['BP12'],
    'Senja' : ['BP13'],
    'Compassvale' : ['SE1'],
    'Rumbia' : ['SE2'],
    'Bakau' : ['SE3'],
    'Kangkar' : ['SE4'],
    'Ranggung' : ['SE5'],
    'Cheng Lim' : ['SW1'],
    'Farmway' : ['SW2'],
    'Kupang' : ['SW3'],
    'Thanggam' : ['SW4'],
    'Fernvale' : ['SW5'],
    'Layar' : ['SW6'],
    'Tongkang' : ['SW7'],
    'Renjong' : ['SW8'],
    'Cove' : ['PE1'],
    'Meridian' : ['PE2'],
    'Coral Edge' : ['PE3'],
    'Riviera' : ['PE4'],
    'Kadaloor' : ['PE5'],
    'Oasis' : ['PE6'],
    'Damai' : ['PE7'],
    'Sam Kee' : ['PW1'],
    'Teck Lee' : ['PW2'],
    'Punggol Point' : ['PW3'],
    'Samudera' : ['PW4'],
    'Nibong' : ['PW5'],
    'Sumang' : ['PW6'],
    'Soo Teck' : ['PW7'],
    'Woodlands North' : ['TE1'],
    'Woodlands South' : ['TE3'],
    'Springleaf' : ['TE4'],
    'Lentor' : ['TE5'],
    'Mayflower' : ['TE6'],
    'Bright Hill' : ['TE7'],
    'Upper Thomson' : ['TE8'],
    'Napier' : ['TE12'],
    'Orchard Boulevard' : ['TE13'],
    'Great World' : ['TE15'],
    'Havelock' : ['TE16'],
    'Maxwell' : ['TE18'],
    'Shenton Way' : ['TE19'],
    'Gardens by the Bay' : ['TE22'],
    'Tanjong Rhu' : ['TE23'],
    'Katong Park' : ['TE24'],
    'Tanjong Katong' : ['TE25'],
    'Marine Parade' : ['TE26'],
    'Marine Terrace' : ['TE27'],
    'Siglap' : ['TE28'],
    'Bayshore' : ['TE29'],
}

module.exports = {
    stations_dict,
}